### ISSUE TITLE
Update to be compatible with Auth0-js 8 or remove Auth0-js?

### ISSUE THREAD

**Issue by evansiroky** [conveyal/woonerf#35]
With some big changes to the package `auth0-js`, some of our code no longer works or makes sense.  The biggest thing affected by us is that the auth0 web client no longer has a `refreshToken` method.  In the [auth0.js migration guide](https://auth0.com/docs/libraries/auth0js/migration-guide#refreshing-tokens) it says:

> In auth0.js v7, the renewIdToken and refreshToken methods were used to renew tokens. In auth0.js v8, refreshing tokens is now done via the renewAuth method. If a user is already authenticated, renewAuth can acquire a new token for that user.

I've discovered two things:

1.  The user info that gets returned from auth0-lock doesn't seem to have a `refreshToken` field
2.  The new method `renewAuth` now has a very different set of arguments to pass in that I'm not sure where to find.  I tried sending just `{}` but I got an error.

In my [latest commit](https://github.com/conveyal/commute/pull/9/commits/f2e6da0b641b87ad671381c49518221d809b08de#diff-220e36d148f62106119d77176e40cad0) in the refactor of the commute app, it seems that this refreshToken / renewAuth logic may not even be necessary anyways.  Also worth noting is that the Quick Start guide for react projects doesn't use auth0-js (only auth0-lock).  I'm wondering if it may make sense to simply remove the auth0-js package and associated logic from woonerf.

**Comment by trevorgerhardt** [comment]
@evansiroky I updated the Analysis UI to use v8 last week and couldn't figure out the renewAuth method either :( 

Turns out all I'm using the client for there is to logout now: https://github.com/conveyal/analysis-ui/blob/dev/lib/utils/auth0.js#L76

I'm all for removing the auth0.js package 👌

**Comment by evansiroky** [comment]
Fixed w/ #36
