### ISSUE TITLE
load of non-index page causes error

### ISSUE THREAD

**Issue by evansiroky** [conveyal/woonerf#40]
Whenever I refresh or load a new page that is not the index page, I get the following error:

<img width="482" alt="screen shot 2017-02-02 at 1 43 09 pm" src="https://cloud.githubusercontent.com/assets/3112493/22569884/1572891a-e94e-11e6-80f6-7bfe09da6943.png">

Not sure if this is a woonerf error or something with my own express setup.

**Comment by trevorgerhardt** [comment]
@evansiroky you figure this out? This is most likely an express error.

**Comment by evansiroky** [comment]
Yeah, it was an express thing.  However, looking into this has inspired me to create #44.
