### ISSUE TITLE
Dependency on deprecated version of Auth0 Lock library

### ISSUE THREAD

**Issue by simonsouth** [conveyal/woonerf#80]
Due to a vulnerability that was found, [Auth0 is deprecating versions prior to 11 of their Lock library](https://auth0.com/docs/migrations/guides/legacy-lock-api-deprecation) and it appears applications that rely on them will cease to work within a few weeks:

> That vulnerability resulted in the deprecation of two endpoints in the Auth0 API, and the libraries and SDKs which used those endpoints. Due to this vulnerability, those endpoints (and thus, the deprecated versions of the libraries) will be removed from service on **July 16, 2018**.

woonerf [currently uses Lock version 10.19.0](https://github.com/conveyal/woonerf/blob/91bb3ce45f6d963d83f49d9e8dc0225e97d3d825/package.json#L20).

Presumably it should be migrated to use Lock v11, though the company notes [this may then require the use of custom domains within Auth0](https://auth0.com/docs/migrations/guides/legacy-lock-api-deprecation#if-you-use-embedded-login), which are a paid feature.

**Comment by trevorgerhardt** [comment]
Removed Auth0 dependency
